


var answerList=[
"Fast Times at Ridgemont High", 
"Valley Girl", 
"Rumble Fish", 
"Peggy Sue Got Married", 
"Raising Arizona", 
"Moonstruck", 
"Never on Tuesday", 
"Vampire's Kiss", 
"Time to Kill", 
"Fire Birds", 
"Wild at Heart", 
"Zandalee", 
"Honeymoon in Vegas", 
"Amos & Andrew", 
"Deadfall", 
"Red Rock West", 
"Guarding Tess", 
"It Could Happen to You", 
"Trapped in Paradise", 
"Kiss of Death", 
"Leaving Las Vegas", 
"The Rock", 
"Con Air", 
"Face/Off", 
"City of Angels", 
"Snake Eyes", 
// "8mm", 
"Bringing Out the Dead", 
"Gone in 60 Seconds", 
"The Family Man", 
"Captain Corelli's Mandolin", 
"Christmas Carol: The Movie", 
"Windtalkers", 
"Adaptation", 
"Sonny", 
"Matchstick Men", 
"National Treasure", 
"Lord of War", 
"The Weather Man", 
"The Ant Bully", 
"The Wicker Man", 
"World Trade Center", 
"Ghost Rider", 
"Grindhouse", 
"Next", 
"National Treasure: Book of Secrets", 
"Bangkok Dangerous", 
"Knowing", 
"G-Force", 
"Astro Boy", 
"Bad Lieutenant: Port of Call New Orleans", 
"Kick-Ass", 
"The Sorcerer's Apprentice", 
"Season of the Witch", 
"Drive Angry", 
"Trespass", 
"Seeking Justice", 
"Ghost Rider: Spirit of Vengeance", 
"Stolen", 
"The Croods", 
"The Frozen Ground", 
"Joe", 
"Outcast", 
"Left Behind", 
"Dying of the Light", 
"The Runner", 
"Pay the Ghost", 
"The Trust", 
"Snowden", 
"USS Indianapolis: Men of Courage", 
"Dog Eat Dog", 
"Army of One", 
"Arsenal", 
"Vengeance: A Love Story", 
"Inconceivable", 
"Mom and Dad", 
"The Humanity Bureau"
];


module.exports=answerList;